openapi: 3.0.0
info:
  title: Test Case
  version: 1.0.0
servers:
  - url: http://localhost:8000
paths:
  /api/tasks:
    get:
      tags:
        - General
      summary: Get Task List
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
